### PR TITLE
Baseline

### PR DESCRIPTION
**Pull request by sventer444**
created a basic form connected to firebase that we can now edit to create our project

### CODE REVIEW

**Comment by GoodGuyGregory** [comment]
This will be the troubled PR. @druss86  and Myself will need to all view this **before** merge to ensure all of our development strategies are in sync.

**Review by GoodGuyGregory — COMMENTED** [review]
💯  thanks for adding this to the repo for reference

**Comment by GoodGuyGregory** [comment]
I will need to checkout this version of the project and take a deeper look at what might be the issue.

**Comment by druss86** [comment]
Looks fine, can always swap it later if we come up with something different.

**Pull request merged**
